name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install dependencies 💿
      run: |
        brew install imagemagick
        curl -L -o elm.pkg https://github.com/elm/compiler/releases/download/0.19.1/installer-for-mac.pkg
        sudo installer -pkg elm.pkg -target /
        rm elm.pkg
 
    - name: Build 🔧
      run: make build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
